scipy2017/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_confirm,\
        password_reset_done, password_reset_complete, password_change,\
        password_change_done
admin.autodiscover()

urlpatterns = patterns('',
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('website.urls', namespace='website')),
    url(r'^2017/', include('website.urls', namespace='website')),
    url(r'^', include('social.apps.django_app.urls', namespace='social')),
    url(r'^', include('django.contrib.auth.urls', namespace='auth')),

    url(r'^forgotpassword/$', password_reset, {'template_name': 'register/password_reset_form.html'}, name="password_reset"),
    url(r'^password_reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm, {'template_name': 'register/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^password_reset/mail_sent/$', password_reset_done, {'template_name': 'register/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^password_reset/complete/$', password_reset_complete, {'template_name': 'register/password_reset_complete.html'},
        name='password_reset_complete'),
    url(r'^changepassword/$', password_change, {'template_name': 'register/password_change_form.html'},
        name='password_change'),
    url(r'^password_change/done/$', password_change_done, {'template_name': 'register/password_change_done.html'},
        name='password_change_done'),
)

website/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = patterns('',
    url(r'^$', 'website.views.home', name='home'),
    # url(r'^contact/$', 'website.views.contact_us', name='contact'),
    url(r'^cfp/$', 'website.views.cfp', name='cfp'),
    url(r'^submit-cfp/$', 'website.views.submitcfp', name='submitcfp'),
    url(r'^submit-cfw/$', 'website.views.submitcfw', name='submitcfw'),
    #url(r'^submit-cfp/$', 'website.views.cfp', name='home'),
    #url(r'^submit-cfw/$', 'website.views.home', name='home'),
    url(r'^accounts/register/$', 'website.views.userregister', name='userregister'),
    #url(r'^accounts/login/$', 'website.views.cfp', name='cfp'),
    url(r'^gallery/$', 'website.views.gallery', name='gallery'),
    # url(r'^view-abstracts/$', 'website.views.view_abstracts', name='view_abstracts'),
    url(r'^view-abstracts/$', 'website.views.view_abstracts', name='view_abstracts'),
    url(r'^abstract-details/(?P<proposal_id>\d+)$', 'website.views.abstract_details', name='abstract_details'),
    url(r'^edit-proposal/(?P<proposal_id>\d+)$', 'website.views.edit_proposal', name='edit_proposal'),
    url(r'^view-abstracts/status_change/$', 'website.views.status_change', name='status_change'),
    url(r'^comment-abstract/(?P<proposal_id>\d+)$', 'website.views.comment_abstract', name='comment_abstract'),
    url(r'^comment-abstract/status/(?P<proposal_id>\d+)$', 'website.views.status', name='status'),
    url(r'^comment-abstract/rate/(?P<proposal_id>\d+)$', 'website.views.rate_proposal', name='rate_proposal'),
    url(r'^process-contact-form/(?P<next_url>\d+)', 'website.views.contact_us', name='contact_us'),
    # url(r'^view-abstracts/download_csv/$','website.views.download_csv', name='download_csv')
    )+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/models.py
from django.db import models
from django.contrib.auth.models import User

from social.apps.django_app.default.models import UserSocialAuth
from scipy2017 import settings
import os

def get_document_dir(instance, filename):
    # ename, eext = instance.user.email.split("@")
    fname, fext = os.path.splitext(filename)
    print "----------------->",instance.user
    return '%s/attachment/%s/%s.%s' % (instance.user, instance.proposal_type, fname+'_'+str(instance.user), fext)

class Proposal(models.Model):
    user = models.ForeignKey(User)
    about_me = models.TextField(max_length=500)
    email = models.CharField(max_length=128)
    phone = models.CharField(max_length = 20)
    title = models.CharField(max_length=250)
    abstract = models.TextField(max_length=700)
    prerequisite = models.CharField(max_length=750)
    duration = models.CharField(max_length = 100)
    attachment = models.FileField(upload_to=get_document_dir)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length = 100, default='Pending', editable=True)
    proposal_type = models.CharField(max_length = 100)
    tags = models.CharField(max_length = 250)

class Ratings(models.Model):
    proposal = models.ForeignKey(Proposal)
    user = models.ForeignKey(User)
    rating = models.CharField(max_length=700)
    
class Comments(models.Model):
    proposal = models.ForeignKey(Proposal)
    user = models.ForeignKey(User)
    comment = models.CharField(max_length=700)
    # rate = models.CharField(max_length =100)

website/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.utils.encoding import force_text
from django.contrib.contenttypes.models import ContentType
from django.template.context import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, redirect
from django.views.decorators.csrf import csrf_exempt
from django.core.context_processors import csrf
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.admin.models import CHANGE
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.db.models import F
import csv
from django.core.mail import EmailMultiAlternatives
import os
from scipy2017.local import *

from website.forms import ProposalForm, UserRegisterForm, UserLoginForm, WorkshopForm, ContactForm
from website.models import Proposal, Comments, Ratings
from social.apps.django_app.default.models import UserSocialAuth
import random
import string


def userregister(request):
    context = {}
    context.update(csrf(request))
    registered_emails = []
    users = User.objects.all()
    for user in users:
        registered_emails.append(user.email)
    if request.user.is_anonymous():
        if request.method == 'POST':
            form = UserRegisterForm(request.POST)
            if form.is_valid():
                data = form.cleaned_data
                if data['email'] in registered_emails:
                    context['form'] = form
                    context['email_registered'] = True
                    return render_to_response('user-register.html', context)
                else:
                    form.save()
                    context['registration_complete'] = True
                    form = UserLoginForm()
                    context['form'] = form
                    context['user'] = request.user
                    return render_to_response('cfp.html', context)
            else:
                context.update(csrf(request))
                context['form'] = form
                return render_to_response('user-register.html', context)
        else:
            form = UserRegisterForm()
        context.update(csrf(request))
        context['form'] = form
        return render_to_response('user-register.html', context)
    else:
        context['user'] = request.user
        return render_to_response('cfp.html', context)

@csrf_exempt 
def gallery(request):
    return render(request, 'gallery.html')

@csrf_exempt 
def contact_us(request,next_url):
    pass
    # user = request.user
    # context = {}
    # if request.method == "POST":
    #     form = ContactForm(request.POST)
    #     sender_name = request.POST['name']
    #     sender_email = request.POST['email']
    #     to = ('scipy@fossee.in',)
    #     subject = "Query from - "+sender_name
    #     message = request.POST['message']
    #     try:
    #         send_mail(subject, message, sender_email, to)
    #         context['mailsent'] = True
    #         context['user'] = user
    #     except:
    #         context['mailfailed'] = True
    #         context['user'] = user
    # return redirect(next_url,context)

@csrf_exempt
def home(request):
    #pass
    context = {}
    if request.user.is_authenticated():
        social_user = request.user
        context.update(csrf(request))
        django_user = User.objects.get(username=social_user)
        context['user'] = django_user
    if request.method == "POST":
        sender_name = request.POST.get('name', None)
        sender_email = request.POST.get('email', None)
        to = (TO_EMAIL, sender_email)
        subject = "Query from - "+str(sender_name)
        message = request.POST.get('message', None)
        try:
            send_mail(subject, message, sender_email, to)
            context['mailsent'] = True
        except:
            context['mailfailed'] = True
    return render_to_response('base.html', context)


def cfp(request):
    if request.method == "POST":
        context = {}
        context.update(csrf(request))
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            if 'next' in request.GET:
                next = request.GET.get('next', None)
                return HttpResponseRedirect(next)
            proposals = Proposal.objects.filter(user = request.user).count()
            context['user'] = user
            context['proposals'] = proposals
            return render_to_response('cfp.html', context)
        else:
            context['invalid'] = True
            context['form'] = UserLoginForm
            context['user'] = user
            return render_to_response('cfp.html', context)
    else:
        form = UserLoginForm()
        context = RequestContext(request, {'request': request,
                                           'user': request.user,
                                           'form': form})
        context.update(csrf(request))
        return render_to_response('cfp.html',
                             context_instance=context)

@login_required
def submitcfp(request):
    context = {}
    if request.user.is_authenticated():
        social_user = request.user
        context.update(csrf(request))
        django_user = User.objects.get(username=social_user)
        context['user'] = django_user
        proposals_a = Proposal.objects.filter(user = request.user, proposal_type = 'ABSTRACT').count()
        if request.method == 'POST':
            form = ProposalForm(request.POST, request.FILES)
            if form.is_valid():
                data = form.save(commit=False)
                data.user = django_user
                data.email = social_user.email
                data.save()
                context['proposal_submit'] = True
                sender_name = "SciPy India 2017"
                sender_email = TO_EMAIL
                subject = "SciPy India 2017 – Talk Proposal Submission Acknowledgment"
                to = (social_user.email, TO_EMAIL)
                message = """
                Dear {0}, <br><br>
                Thank you for showing interest & submitting a talk proposal at SciPy India 2017 conference for the talk titled <b>“{1}”</b>. Reviewal of the proposals will start once the CFP closes.
                <br><br>You will be notified regarding comments/selection/rejection of your talk via email.
                Visit this {2} link to view status of your submission.
                <br>Thank You ! <br><br>Regards,<br>SciPy India 2017,<br>FOSSEE - IIT Bombay.
                """.format(
                social_user.first_name,
                request.POST.get('title', None),
                'http://scipy.in/2017/view-abstracts/',  )
                email = EmailMultiAlternatives(
                subject,'',
                sender_email, to,
                headers={"Content-type":"text/html;charset=iso-8859-1"}
                )
                email.attach_alternative(message, "text/html")
                email.send(fail_silently=True)
                return render_to_response('cfp.html', context)
            else:
                context['proposal_form'] =  form
                context['proposals_a'] = proposals_a
                return render_to_response('submit-cfp.html', context)
        else:
            form = ProposalForm()
            context['proposals_a'] = proposals_a 
            context['proposal_form'] = form
        return render_to_response('submit-cfp.html', context) #when link clicked
    else:
        context['login_required'] = True
        return render_to_response('cfp.html', context)


@login_required
def submitcfw(request):
    context = {}
    if request.user.is_authenticated():
        social_user = request.user
        context.update(csrf(request))
        django_user = User.objects.get(username=social_user)
        context['user'] = django_user
        proposals_w = Proposal.objects.filter(user = request.user, proposal_type = 'WORKSHOP').count()
        if request.method == 'POST':
            form = WorkshopForm(request.POST, request.FILES)
            if form.is_valid():
                data = form.save(commit=False)
                data.user = django_user
                data.email = social_user.email
                data.save()
                context['proposal_submit'] = True
                sender_name = "SciPy India 2017"
                sender_email = TO_EMAIL
                subject = "SciPy India 2017 – Workshop Proposal Submission Acknowledgment"
                to = (social_user.email, TO_EMAIL)
                message = """
                Dear {0}, <br><br>
                Thank you for showing interest & submitting a workshop proposal at SciPy India 2017 conference for the workshop titled <b>“{1}”</b>. Reviewal of the proposals will start once the CFP closes.
                <br><br>You will be notified regarding comments/selection/rejection of your workshop via email.
                Visit this {2} link to view status of your submission.
                <br>Thank You ! <br><br>Regards,<br>SciPy India 2017,<br>FOSSEE - IIT Bombay.
                """.format(
                social_user.first_name,
                request.POST.get('title', None),
                'http://scipy.in/2017/view-abstracts/',  )
                email = EmailMultiAlternatives(
                subject,'',
                sender_email, to,
                headers={"Content-type":"text/html;charset=iso-8859-1"}
                )
                email.attach_alternative(message, "text/html")
                email.send(fail_silently=True)
                return render_to_response('cfp.html', context)
            else:
                context['proposal_form'] =  form
                context['proposals_w'] = proposals_w

website/templates/register/password_change_done.html
{% load static %}

<!DOCTYPE HTML>
<html>
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="">
      <link rel="icon" href="{% static 'img/fevicon.png'%}" type="icon">
      <title>SciPy India 2017</title>
      <!-- Bootstrap core CSS -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <!-- Custom styles for this template -->
      <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet">
   </head>
  <body>


      {% block header %}
       <header id="header1" style="background-color: #01c3d9;">
        <center>
            <h1>SciPy India 2017</h1>
            <h2>Reset Password</h2>
        </center>
       </header> 
{% endblock %}

{% block content %}
<div id="wrapper" style="margin-left: 10%;">
<div id="main">
<section id="content" class="main">

<script type="text/javascript">
	window.setTimeout(function()
	{   
		location.href="{{ URL_ROOT }}/accounts/"
	}, 2000);
</script>
<h3>Your password has been changed successfully.</h3>
<h4>Redirecting ...</h4>
</section>
</div>
</div>
{% endblock %}

website/templates/register/password_change_form.html
{% load static %}

<!DOCTYPE HTML>
<html>
 <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="">
      <link rel="icon" href="{% static 'img/fevicon.png'%}" type="icon">
      <title>SciPy India 2017</title>
      <!-- Bootstrap core CSS -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <!-- Custom styles for this template -->
      <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet">
   </head>
  <body>


      {% block header %}
       <header id="header1" style="background-color: #01c3d9;">
        <center>
            <h1>SciPy India 2017</h1>
            <h2>Reset Password</h2>
        </center>
</header> 
{% endblock %}

{% block content %}
<div id="wrapper" style="margin-left: 10%;">
<div id="main">
<section id="content" class="main">
<br>
<form action="" method="post" >
  {% csrf_token %}
  <center>
  <table class=span1>
  {{ form }}
  </table>
  </center>
  <center><button class="btn" type="submit">Change Password</button>
  <button class="btn btn-primary gradient" type="button" name="button" onClick='location.replace("{{URL_ROOT}}/accounts/");'>Cancel</button></center>
</form>
</section>
</div>
</div>
{% endblock %}

website/templates/register/password_reset_complete.html
{% load static %}

<!DOCTYPE HTML>
<html>
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="">
      <link rel="icon" href="{% static 'img/fevicon.png'%}" type="icon">
      <title>SciPy India 2017</title>
      <!-- Bootstrap core CSS -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <!-- Custom styles for this template -->
      <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet">
   </head>
  <body>


      {% block header %}
       <header id="header1" style="background-color: #01c3d9;">
        <center>
            <h1>SciPy India 2017</h1>
            <h2>Reset Password</h2>
        </center>
        </header> 
{% endblock %}

{% block content %}
<div id="wrapper" style="margin-left: 10%;">
<div id="main">
<section id="content" class="main">
<br>
<p>Your password has been reset. </p>
<p>Please <a href="{% url 'website:cfp' %}">Log in</a> with your new password.</p>
</section>
</div>
</div>
{% endblock %}

website/templates/register/password_reset_confirm.html
{% load static %}

<!DOCTYPE HTML>
<html>
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="">
      <link rel="icon" href="{% static 'img/fevicon.png'%}" type="icon">
      <title>SciPy India 2017</title>
      <!-- Bootstrap core CSS -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <!-- Custom styles for this template -->
      <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet">
   </head>
  <body>


      {% block header %}
       <header id="header1" style="background-color: #01c3d9;">
       <center>
            <h1>SciPy India 2017</h1>
            <h2>Reset Password</h2>
       </center>
       </header> 
{% endblock %}

{% block content %}
<div id="wrapper" style="margin-left: 10%;">
<div id="main">
<section id="content" class="main">
    {% if validlink %}
    <br>
   <p>Please enter your new password twice.</p>
           <br>
        <form action="" method="post">
            <div style="display:none">
                <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
            </div>
            <table>
              <colgroup>
                <col width="40%" />
                     <col width="60%" />
              </colgroup>
                <tr>
                    <td>{{ form.new_password1.errors }}
                        <label for="id_new_password1" >New password:</label></td>
                    <td>{{ form.new_password1 }}</td>
                </tr>
                <tr>
                    <td>{{ form.new_password2.errors }}
                        <label for="id_new_password2" >Confirm password:</label></td>
                    <td>{{ form.new_password2 }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td><br> <button class= "btn btn-sm btn-primary gradient" type="submit" onclick="return checkform(this);">Submit</button> 
                </tr>
                <br>
            </table>
        </form>
    {% else %}
        <p>The password reset link is invalid,
        possibly because it has already been used. <br />
        Please request a new password reset.</p><br/>
    {% endif %}
</section>
</div>
</div>

<script>
function checkform(form) { 
    // alert("in");
    var pwd1 = document.getElementById("id_new_password1");
    // alert(pwd1.value);
    var pwd2 = document.getElementById("id_new_password2");
    //return false;
    if(pwd1.value.length && pwd2.value.length < 8) { 
     
        alert("Error: Password must contain at least eight characters!"); 
        pwd1.focus();     
        pwd1.value = "";
        pwd2.value = "";
        return false;      
    }   
}

</script>
{% endblock %}

website/templates/register/password_reset_done.html
{% load static %}

<!DOCTYPE HTML>
<html>
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="">
      <link rel="icon" href="{% static 'img/fevicon.png'%}" type="icon">
      <title>SciPy India 2017</title>
      <!-- Bootstrap core CSS -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <!-- Custom styles for this template -->
      <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet">
   </head>
  <body>

<center>
      {% block header %}
       <header id="header1"  style="background-color: #01c3d9;">
       <br>
            <h1>SciPy India 2017</h1>
            <h2>Reset Password</h2>
            <br>
</header>
</center> 
{% endblock %}


{% block content %}
<div id="wrapper">
<div id="main">
<section id="content" class="main" style="margin-left: 10%;">
<br>
	If an account exists with this email, you would receive the password reset instructions shortly. Please  check your spam folder too.<br/>
</section>
</div>
</div>
 {% endblock %}

website/templates/register/password_reset_form.html
{% load static %}

<!DOCTYPE HTML>
<html>
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="">
      <link rel="icon" href="{% static 'img/fevicon.png'%}" type="icon">
      <title>SciPy India 2017</title>
      <!-- Bootstrap core CSS -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <!-- Custom styles for this template -->
      <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet">
   </head>
  <body>
{% include 'navbar.html' %}

<center>

      {% block header %}
       <header id="header1" style="background-color: #01c3d9;">
       <br>
            <h1>SciPy India 2017</h1>
            <h2>Reset Password</h2>
            <br>
</header> 
</center>
{% endblock %}

{% block content %}
<div id="wrapper" style="margin-left: 10%;">
<div id="main">
<section id="content" class="main">
<br>
<div><h4> Recovery Email </h4></div>
<br>
 Kindly enter your email ID used for registration. The password reset link will be mailed to the same.
<br><br>
<form action="" method="post">
    {% csrf_token %}
   {{ form.email.errors }}
    <p><label for="id_email">E-mail address:</label> {{ form.email }} 

      <br/>
      <br><input type="submit" class ="btn btn-primary gradient" style="border: none;" value="Reset Password" /></p>

    <!-- <button class="btn btn-sm btn-primary" type="submit">Request</button>
    <a class="btn btn-sm " href="{{URL_ROOT}}/accounts/login/">Cancel</a> -->
</form>

<br>

</section>
</div>
</div>

{% endblock %}