scipy2017/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_confirm,\
        password_reset_done, password_reset_complete, password_change,\
        password_change_done
admin.autodiscover()

urlpatterns = patterns('',
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('website.urls', namespace='website')),
    url(r'^2017/', include('website.urls', namespace='website')),
    url(r'^', include('social.apps.django_app.urls', namespace='social')),
    url(r'^', include('django.contrib.auth.urls', namespace='auth')),

    url(r'^forgotpassword/$', password_reset, {'template_name': 'register/password_reset_form.html'}, name="password_reset"),
    url(r'^password_reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm, {'template_name': 'register/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^password_reset/mail_sent/$', password_reset_done, {'template_name': 'register/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^password_reset/complete/$', password_reset_complete, {'template_name': 'register/password_reset_complete.html'},
        name='password_reset_complete'),
    url(r'^changepassword/$', password_change, {'template_name': 'register/password_change_form.html'},
        name='password_change'),
    url(r'^password_change/done/$', password_change_done, {'template_name': 'register/password_change_done.html'},
        name='password_change_done'),
)

website/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = patterns('',
    url(r'^$', 'website.views.home', name='home'),
    # url(r'^contact/$', 'website.views.contact_us', name='contact'),
    url(r'^cfp/$', 'website.views.cfp', name='cfp'),
    url(r'^submit-cfp/$', 'website.views.submitcfp', name='submitcfp'),
    url(r'^submit-cfw/$', 'website.views.submitcfw', name='submitcfw'),
    #url(r'^submit-cfp/$', 'website.views.cfp', name='home'),
    #url(r'^submit-cfw/$', 'website.views.home', name='home'),
    url(r'^accounts/register/$', 'website.views.userregister', name='userregister'),
    #url(r'^accounts/login/$', 'website.views.cfp', name='cfp'),
    url(r'^gallery/$', 'website.views.gallery', name='gallery'),
    # url(r'^view-abstracts/$', 'website.views.view_abstracts', name='view_abstracts'),
    url(r'^view-abstracts/$', 'website.views.view_abstracts', name='view_abstracts'),
    url(r'^abstract-details/(?P<proposal_id>\d+)$', 'website.views.abstract_details', name='abstract_details'),
    url(r'^edit-proposal/(?P<proposal_id>\d+)$', 'website.views.edit_proposal', name='edit_proposal'),
    url(r'^view-abstracts/status_change/$', 'website.views.status_change', name='status_change'),
    url(r'^comment-abstract/(?P<proposal_id>\d+)$', 'website.views.comment_abstract', name='comment_abstract'),
    url(r'^comment-abstract/status/(?P<proposal_id>\d+)$', 'website.views.status', name='status'),
    url(r'^comment-abstract/rate/(?P<proposal_id>\d+)$', 'website.views.rate_proposal', name='rate_proposal'),
    url(r'^process-contact-form/(?P<next_url>\d+)', 'website.views.contact_us', name='contact_us'),
    # url(r'^view-abstracts/download_csv/$','website.views.download_csv', name='download_csv')
    )+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/models.py
from django.db import models
from django.contrib.auth.models import User

from social.apps.django_app.default.models import UserSocialAuth
from scipy2017 import settings
import os

def get_document_dir(instance, filename):
    # ename, eext = instance.user.email.split("@")
    fname, fext = os.path.splitext(filename)
    print "----------------->",instance.user
    return '%s/attachment/%s/%s.%s' % (instance.user, instance.proposal_type, fname+'_'+str(instance.user), fext)

class Proposal(models.Model):
    user = models.ForeignKey(User)
    about_me = models.TextField(max_length=500)
    email = models.CharField(max_length=128)
    phone = models.CharField(max_length = 20)
    title = models.CharField(max_length=250)
    abstract = models.TextField(max_length=700)
    prerequisite = models.CharField(max_length=750)
    duration = models.CharField(max_length = 100)
    attachment = models.FileField(upload_to=get_document_dir)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length = 100, default='Pending', editable=True)
    proposal_type = models.CharField(max_length = 100)
    tags = models.CharField(max_length = 250)

class Ratings(models.Model):
    proposal = models.ForeignKey(Proposal)
    user = models.ForeignKey(User)
    rating = models.CharField(max_length=700)
    
class Comments(models.Model):
    proposal = models.ForeignKey(Proposal)
    user = models.ForeignKey(User)
    comment = models.CharField(max_length=700)
    # rate = models.CharField(max_length =100)

website/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.utils.encoding import force_text
from django.contrib.contenttypes.models import ContentType
from django.template.context import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, redirect
from django.views.decorators.csrf import csrf_exempt
from django.core.context_processors import csrf
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.admin.models import CHANGE
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.db.models import F
import csv
from django.core.mail import EmailMultiAlternatives
import os
from scipy2017.local import *

from website.forms import ProposalForm, UserRegisterForm, UserLoginForm, WorkshopForm, ContactForm
from website.models import Proposal, Comments, Ratings
from social.apps.django_app.default.models import UserSocialAuth
import random
import string


def userregister(request):
    context = {}
    context.update(csrf(request))
    registered_emails = []
    users = User.objects.all()
    for user in users:
        registered_emails.append(user.email)
    if request.user.is_anonymous():
        if request.method == 'POST':
            form = UserRegisterForm(request.POST)
            if form.is_valid():
                data = form.cleaned_data
                if data['email'] in registered_emails:
                    context['form'] = form
                    context['email_registered'] = True
                    return render_to_response('user-register.html', context)
                else:
                    form.save()
                    context['registration_complete'] = True
                    form = UserLoginForm()
                    context['form'] = form
                    context['user'] = request.user
                    return render_to_response('cfp.html', context)
            else:
                context.update(csrf(request))
                context['form'] = form
                return render_to_response('user-register.html', context)
        else:
            form = UserRegisterForm()
        context.update(csrf(request))
        context['form'] = form
        return render_to_response('user-register.html', context)
    else:
        context['user'] = request.user
        return render_to_response('cfp.html', context)

@csrf_exempt 
def gallery(request):
    return render(request, 'gallery.html')

@csrf_exempt 
def contact_us(request,next_url):
    pass
    # user = request.user
    # context = {}
    # if request.method == "POST":
    #     form = ContactForm(request.POST)
    #     sender_name = request.POST['name']
    #     sender_email = request.POST['email']
    #     to = ('scipy@fossee.in',)
    #     subject = "Query from - "+sender_name
    #     message = request.POST['message']
    #     try:
    #         send_mail(subject, message, sender_email, to)
    #         context['mailsent'] = True
    #         context['user'] = user
    #     except:
    #         context['mailfailed'] = True
    #         context['user'] = user
    # return redirect(next_url,context)

@csrf_exempt
def home(request):
    #pass
    context = {}
    if request.user.is_authenticated():
        social_user = request.user
        context.update(csrf(request))
        django_user = User.objects.get(username=social_user)
        context['user'] = django_user
    if request.method == "POST":
        sender_name = request.POST.get('name', None)
        sender_email = request.POST.get('email', None)
        to = (TO_EMAIL, sender_email)
        subject = "Query from - "+str(sender_name)
        message = request.POST.get('message', None)
        try:
            send_mail(subject, message, sender_email, to)
            context['mailsent'] = True
        except:
            context['mailfailed'] = True
    return render_to_response('base.html', context)


def cfp(request):
    if request.method == "POST":
        context = {}
        context.update(csrf(request))
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            if 'next' in request.GET:
                next = request.GET.get('next', None)
                return HttpResponseRedirect(next)
            proposals = Proposal.objects.filter(user = request.user).count()
            context['user'] = user
            context['proposals'] = proposals
            return render_to_response('cfp.html', context)
        else:
            context['invalid'] = True
            context['form'] = UserLoginForm
            context['user'] = user
            return render_to_response('cfp.html', context)
    else:
        form = UserLoginForm()
        context = RequestContext(request, {'request': request,
                                           'user': request.user,
                                           'form': form})
        context.update(csrf(request))
        return render_to_response('cfp.html',
                             context_instance=context)

@login_required
def submitcfp(request):
    context = {}
    if request.user.is_authenticated():
        social_user = request.user
        context.update(csrf(request))
        django_user = User.objects.get(username=social_user)
        context['user'] = django_user
        proposals_a = Proposal.objects.filter(user = request.user, proposal_type = 'ABSTRACT').count()
        if request.method == 'POST':
            form = ProposalForm(request.POST, request.FILES)
            if form.is_valid():
                data = form.save(commit=False)
                data.user = django_user
                data.email = social_user.email
                data.save()
                context['proposal_submit'] = True
                sender_name = "SciPy India 2017"
                sender_email = TO_EMAIL
                subject = "SciPy India 2017 – Talk Proposal Submission Acknowledgment"
                to = (social_user.email, TO_EMAIL)
                message = """
                Dear {0}, <br><br>
                Thank you for showing interest & submitting a talk proposal at SciPy India 2017 conference for the talk titled <b>“{1}”</b>. Reviewal of the proposals will start once the CFP closes.
                <br><br>You will be notified regarding comments/selection/rejection of your talk via email.
                Visit this {2} link to view status of your submission.
                <br>Thank You ! <br><br>Regards,<br>SciPy India 2017,<br>FOSSEE - IIT Bombay.
                """.format(
                social_user.first_name,
                request.POST.get('title', None),
                'http://scipy.in/2017/view-abstracts/',  )
                email = EmailMultiAlternatives(
                subject,'',
                sender_email, to,
                headers={"Content-type":"text/html;charset=iso-8859-1"}
                )
                email.attach_alternative(message, "text/html")
                email.send(fail_silently=True)
                return render_to_response('cfp.html', context)
            else:
                context['proposal_form'] =  form
                context['proposals_a'] = proposals_a
                return render_to_response('submit-cfp.html', context)
        else:
            form = ProposalForm()
            context['proposals_a'] = proposals_a 
            context['proposal_form'] = form
        return render_to_response('submit-cfp.html', context) #when link clicked
    else:
        context['login_required'] = True
        return render_to_response('cfp.html', context)


@login_required
def submitcfw(request):
    context = {}
    if request.user.is_authenticated():
        social_user = request.user
        context.update(csrf(request))
        django_user = User.objects.get(username=social_user)
        context['user'] = django_user
        proposals_w = Proposal.objects.filter(user = request.user, proposal_type = 'WORKSHOP').count()
        if request.method == 'POST':
            form = WorkshopForm(request.POST, request.FILES)
            if form.is_valid():
                data = form.save(commit=False)
                data.user = django_user
                data.email = social_user.email
                data.save()
                context['proposal_submit'] = True
                sender_name = "SciPy India 2017"
                sender_email = TO_EMAIL
                subject = "SciPy India 2017 – Workshop Proposal Submission Acknowledgment"
                to = (social_user.email, TO_EMAIL)
                message = """
                Dear {0}, <br><br>
                Thank you for showing interest & submitting a workshop proposal at SciPy India 2017 conference for the workshop titled <b>“{1}”</b>. Reviewal of the proposals will start once the CFP closes.
                <br><br>You will be notified regarding comments/selection/rejection of your workshop via email.
                Visit this {2} link to view status of your submission.
                <br>Thank You ! <br><br>Regards,<br>SciPy India 2017,<br>FOSSEE - IIT Bombay.
                """.format(
                social_user.first_name,
                request.POST.get('title', None),
                'http://scipy.in/2017/view-abstracts/',  )
                email = EmailMultiAlternatives(
                subject,'',
                sender_email, to,
                headers={"Content-type":"text/html;charset=iso-8859-1"}
                )
                email.attach_alternative(message, "text/html")
                email.send(fail_silently=True)
                return render_to_response('cfp.html', context)
            else:
                context['proposal_form'] =  form
                context['proposals_w'] = proposals_w

website/templates/cfp.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="">
      <link rel="icon" href="{% static 'img/fevicon.png'%}" type="icon">
      <title>SciPy India 2017</title>
      <!-- Bootstrap core CSS -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <!-- Custom styles for this template -->
      <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet">
   </head>
   <body data-spy="scroll" data-target=".navbar" data-offset="50">
      {% include 'navbar.html' %}
      {% block content %}
      <center>
         <div style="background-color: #01c3d9;width: auto;">
            <h1 style="color:black;font-family: Arial;font-weight: bold">
               <span style="color:black;font-size: 2.25em;font-family: Arial;font-weight: bold">SciPy
               </span>
             India
            </h1>
            <p style="color:#111111; font-size:28px;font-family: Merriweather;" >November 29 & 30 - 2017
            </p>
         </div>
      </center>
      <div class="container">
         <p>
         <center>
            {% if user and not user.is_anonymous %}
            <h2>Submit Proposal</h2>
            {% else %}
            <h2>Login</h2>
            {% endif %}
         </center>
         </p>
         {% if proposal_submit %}
         <center>
            <table>
               <tr>
                  <td>
                     <p>Thank You for your submission. Your proposal has been saved successfully and is under review. You can check the status of submission <a href="{% url 'website:view_abstracts' %}">here 
                        </a>!
                     </p>
                  </td>
               </tr>
            </table>
         </center>
         {% endif %}
         {% if registration_complete %}
         <center>
            <p>Thank You for your registration. You can now log in by clicking  <a href="{% url 'website:cfp' %}">here 
               </a>!
            </p>
            <br/><br/>
         </center>
         {% endif %}
         {% if user and not user.is_anonymous and not login_required %}
         <p>We invite you to submit proposals for talks or workshops to be presented at SciPy 2017. The time duration for talks is 15 or 30 minutes and for workshops is 2 to 4 hours. There will be two parallel tracks for the workshops this year.  One track is meant for beginners and the other is for advanced users.     
         </p>
         <span>
            <h2>
               <u>Important Dates</u>
            </h2>
         </span>
         <ul>
            <li>Call for proposals opens: 
               <b>15<sup>th</sup> Sept. 2017</b>
            </li>
            <li>Last date for submission of proposals: 
               <b>10<sup>th</sup> Nov. 2017</b>
            </li>
            <li>Announcement of selected proposals: 
               <b>15<sup>th</sup> Nov. 2017</b>
            </li>
         </ul>
         <br/>
         {% if user.is_superuser %}
         <center>
            <a href="{% url 'website:view_abstracts' %}" class="btn btn-info">View Proposals</a>
         </center>
         {% else %}
         <center>
            <a href="{% url 'website:view_abstracts' %}" class="btn btn-info">View Proposals</a>
         </center>
         {% endif %}
         {% else %}
         
         <hr>
         <div class="row">
            <div class="col-sm-4">
               <span>
                  <h2>
                     <u>Login</u>
                  </h2>
               </span>
               <p>Login/Register to Submit a Proposal</p>
               {% if invalid %}
               <p style="color:red; font-size:15px;">* Invalid Username/Password</p>
               {% endif %}
               <!-- <div id = "my_form"> -->
               <form action="" method="POST">
                  {{ form.as_p }}
                  <button class="button special" name ="login" type="submit">Login</button>
                  <br/><br/>
                  <a style="padding-right : 20px;" href="{% url 'website:userregister' %}" class="btn btn btn-primary">Create an Account
                  </a><br>
                  <a href="/2017/forgotpassword/">Forgot Password?</a>
                  {% csrf_token %}
               </form>
               <!-- </div> -->
               <p>Or Sign in with:&nbsp;<br>
                  <a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}" class="btn btn-social-icon "  style="color:#d34836;">
                     <i class="fa fa-google-plus-square" style="font-size:40px;"></i>
                  </a>&nbsp;
                  <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}" class=" btn btn-social-icon" style="color:#3b5998">
                     <i class="fa fa-facebook-square" style="font-size:40px;"></i>
                  </a>
               </p>
               <br>
               <p>
               <h4>
                  <u>Important Dates</u>
               </h4>
               <ul style="margin-left: -7%;">
                  <li>Call for proposals opens: <br>
                     <b>15<sup>th</sup> Sept. 2017</b>
                  </li>
                  <li>Last date for submission of proposals: <br>
                     <b>10<sup>th</sup> Nov. 2017</b>
                  </li>
                  <li>Announcement of selected proposals: <br>
                     <b>15<sup>th</sup> Nov. 2017</b>
                  </li>
               </ul>
               </p>
            </div>
                          
                 <div class="col-sm-4" align="justify" style="background-color: #cef3f8;">
                 <br>
                        <h4 class="panel-title">
                        Guidelines for a Proposal
                        </h4>
                           <ul style="margin-left: -6%;">
                              <li>The project should be an actual implementation rather than just an idea.</li>
                              <li>Besides implementation, the submission can also be about experiences and usage of Python, Python-based tools and libraries for research or teaching.</li>
                              <li>Abstract should be of 300 to 700 words describing the topic, including its relevance to scientific computing or the use of Python in education.</li>
                              <li>All selected proposals must be presented at the conference by atleast one author.</li>
                           </ul>
                        </div>
                  <div class="col-sm-4" align="justify" style="background-color: #8cc9f0;">
                  <br>
                        <h4 class="panel-title">
                           Guidelines for a Workshop
                        </h4>
                     
                        <ul style="margin-left: -6%;">
                           <li>There are two parallel tracks, one for beginners and one for advanced users.</li>
                           <li>The workshops should be hands-on with plenty of exercises for the users.</li>
                           <li>It is advisable to pick particular problem(s) and orient your workshop around how to solve those using the package you plan to talk about.</li>
                           <li>Provide us with links to any resources you have already prepared for the workshop.</li>
                        </ul>
                     </div>
                     
                  </div>
               

         </div>
         {% endif %}   
      </div>
      {% endblock %}
      {% include 'footer.html' %}
   </body>
</html>

website/templates/down.html
<center>
<p>We are making some changes to the website.</p>
<p>We will be back soon. Stay tuned !</p>
</center>

website/templates/view-abstracts.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="{% static 'img/fevicon.png'%}" type="icon">
        <title>SciPy India 2017</title>
        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet">
    </head>
    <body data-spy="scroll" data-target=".navbar" data-offset="50">
        {% include 'navbar.html' %}
        {% block content %}
        <div class="container">
            <p>
            <center>
                <h2>View Proposals</h2>
            </center>
            </p>
            {% if not proposals %}
            <center>
                <h3>Proposals are no longer accepted</h3>
                <!-- You have not submitted any proposal.<br> <br>
                <a href="{% url 'website:submitcfp' %}" class ="btn btn-info" role="button"> Submit paper  </a>
                <a href="{% url 'website:submitcfw' %}" class ="btn btn-info" role="button">Submit workshop </a> -->
            </center>
            {% else %}
            {% if user.is_superuser  %}
            <div style="float:right"><input type="submit" id="dump" class ="btn btn-info"  value="Export as csv" name="dump"/></div>
            <br>
            {% endif %}
            <form action="{% url 'website:status_change' %}" method="post" onsubmit="return confirm('Are You Sure?');">
                {% csrf_token %}
                <p>
                <div class="table-responsive">
                    <table id = "myTable" width="100%" cellpadding="10" class="table-bordered table-hover tablesorter">
                        <colgroup>
                            {% if user.is_superuser  %}
                            <col width="15%" />
                            <col width="20%" />
                            <col width="10%" />
                            <col width="30%" />
                            <col width="10%" />
                            <col width="10%" />
                            {% else %}
                            <col width="15%" />
                            <col width="70%" />
                            <col width="10%" />
                            <col width="10%" />
                            <col width="20%" />
                            {% endif %}
                        </colgroup>
                            {% if user.is_superuser  %}
                        <th style="text-align: center;">
                        </th>
                        <th style="text-align: center;">Speaker
                            {% endif %}
                        <th style="text-align: center;"> Type
                        <th style="text-align: center;"> Title
                            {% if not user.is_superuser %}
                        <th style="text-align: center;"> View
                            {% endif %}
                            {% if user.is_superuser %}
                        <th style="text-align: center;">
                            <center> Duration</center>
                            {% else %}
                        <th style="text-align: center;"> Comments
                            {% endif %}
                        <th style="text-align: center;"> Status
                            {% for proposal in proposals %}
                        <tr>
                            {% if user.is_superuser %}
                            <td style="text-align: center;">
                                {% if proposal.status = 'Rejected' %}
                                {% else %}
                                <center> <input type = "checkbox" name="delete_proposal" value = {{proposal.id}}></input></center>
                            </td>
                            {% endif %}
                            <td style="text-align: center;">
                                {{ proposal.user.get_full_name}}
                            </td>
                            {% endif %}
                            <td style="text-align: center;"> {{proposal.proposal_type }} </td>
                            {% if user.is_superuser  %}
                            <td style="white-space: nowrap; text-overflow:ellipsis; overflow: hidden; max-width:.5px;"><a title="Title : {{proposal.title}}, Tags: {{proposal.tags}}" href="{% url 'website:comment_abstract' proposal.id %}">{{proposal.title}}</a> </td>
                            {% else %}
                            <td  style="white-space: nowrap; text-overflow:ellipsis; overflow: hidden; max-width:.5px;"> {{proposal.title}}</td>
                            <td style="text-align: center;"><a href="{% url 'website:abstract_details' proposal.id %}">View</a> </td>
                            {% endif %}
                            <td style="text-align: center;">
                                {% if user.is_superuser %}
                                <center>{{ proposal.duration }}
                                    {% if proposal.proposal_type == 'ABSTRACT' %}
                                    Mins{% else %} Hrs {% endif %}
                                </center>
                                {% else %}
                                {{proposal.comments_set.count}}
                                {% endif %}
                            </td>
                            <td style="text-align: center;">
                                {% if proposal.status = 'Accepted' %}
                                <h5 style="color:green;">{{proposal.status}}</h5>
                                {% elif proposal.status = 'Rejected' %}
                                <h5 style="color:red;">{{proposal.status}}</h5>
                                {% elif proposal.status = 'Commented' %}
                                <h5 style="color:brown;">{{proposal.status}}</h5>
                                {% elif proposal.status = 'Edit' %}
                                {% if user.is_superuser %}
                                <h5 style="color:grey;">{{proposal.status}}</h5>
                                {% else %}
                                <a href="{% url 'website:edit_proposal' proposal.id %}">{{proposal.status}}</a>
                                {% endif %}
                                {% else %}  
                                <h5 style="color:blue;">{{proposal.status}}</h5>
                                {% endif %}
                            </td>
                           <!--
                            <div>   
                                {% if not user.is_superuser and type == 'ABSTRACT' %}
                                <a href="{% url 'website:submitcfw' %}" class ="btn btn-info" role="button">Submit workshop </a>    
                                {% elif not user.is_superuser and type == 'WORKSHOP' %}
                                <a href="{% url 'website:submitcfp' %}" class ="btn btn-info" role="button"> Submit paper  </a>
                                {% elif not user.is_superuser%}
                                {% endif %}
                            </div>-->
                         </tr>
                        {% endfor %}
                </table>
                </div><br>
                </p>


                {% if user.is_superuser  %}
                <input type="submit" id="delete" class ="btn btn-info" value="Delete" name="delete"/>
                <center>
                    <input type="submit" id="accept" class ="btn btn-info" value="Accept" name="accept"/>
                    <input type="submit" id="rejected" class ="btn btn-info"  value="Reject" name="reject"/>
                    <input type="submit" id="resubmit" class ="btn btn-info"  value="Resubmit" name="resubmit"/>
                </center>
                {% endif %}
            </form>
            {% endif %}
        </div>
        {% endblock %}
        {% include 'footer.html' %}
    </body>
</html>